# Generated by Django 3.0 on 2020-04-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanjin2',
            name='main_word',
            field=models.CharField(max_length=5),
        ),
    ]
