# Generated by Django 3.0 on 2020-04-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_auto_20200409_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanjin2',
            name='main_word',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
